---
title: "Homework"
---

+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
| Assignment # | Description                                   | Due Date  | Value | Solutions                                          |
+==============+===============================================+===========+=======+====================================================+
|    0         | Review/Foundations.  Probability, a little    | 5 pm,     |  1    |  On GitHub                                         |
|              | calculus, and R.                              | 1/27/2020 |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps0/ps0_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps0/ps0_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part:                                       |           |       |                                                    |
|              | Distributed via GitHub.                       |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    1         | $\chi^2$, $t$, and $F$ distributions.         | 5 pm,     |  1    |                                                    |
|              | Maximum likelihood estimation.                | 2/5/2020  |       |                                                    |
|              | Note: for this assignment, do the written     |           |       |                                                    |
|              | part before the R part.                       |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps1/ps1_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps1/ps1_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part:                                       |           |       |                                                    |
|              | Distributed via GitHub.                       |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    2         | Method of moments and numerical approaches to | 5 pm,     |  1    |                                                    |
|              | maximum likelihood estimation.                | 2/14/2020 |       |                                                    |
|              | Note: for this assignment, do the written     |           |       |                                                    |
|              | part before the R part.                       |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps2/ps2_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps2/ps2_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part:                                       |           |       |                                                    |
|              | Distributed via GitHub.                       |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+
|    3         | Bias, variance, MSE, and Bayesian inference   | 5 pm,     |  1    |                                                    |
|              | with conjugate priors.                        | 2/26/2020 |       |                                                    |
|              | Note: for this assignment, do the written     |           |       |                                                    |
|              | part before the R part.                       |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | Written part:                                 |           |       |                                                    |
|              | [pdf](homework/ps3/ps3_written.pdf)           |           |       |                                                    |
|              | [Rmd](homework/ps3/ps3_written.Rmd)           |           |       |                                                    |
|              |                                               |           |       |                                                    |
|              | R part:                                       |           |       |                                                    |
|              | Distributed via GitHub.                       |           |       |                                                    |
+--------------+-----------------------------------------------+-----------+-------+----------------------------------------------------+

