---
  title: "Schedule"
---
  
  **Click on the text like "Week 1: Jan 20 -- 24" to expand or collapse the items we covered in that week.**
  
  I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
      sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Jan 20 -- Jan 24", "

#### Wed, Jan 22
 * **In class**, we will work on:
    * Discuss [syllabus](syllabus/syllabus_stat_343.pdf), overview of course
    * Review of prerequisites
        * Topics from probability: [pdf](resources/probability/probability.pdf) (also posted on resources page)
        * Practice examples for probability: [pdf](materials/20200122_probability/probability_practice.pdf) Solutions: [pdf](materials/20200122_probability/probability_practice_sol.pdf)
        * Common probability distributions: [pdf](resources/probability/probability_distributions.pdf) (also posted on resources page; you don't need to memorize this material)
        * Topics from calculus (not discussed today, please review after class): [pdf](resources/calculus/calculus.pdf) (also posted on resources page)
 * **After class**, please do the following:
    * **Register for GitHub** [here](https://github.com) if you haven't already; I will ask you to provide your GitHub user name in the questionairre below.
    * **Fill out** a brief [questionnairre](https://docs.google.com/forms/d/e/1FAIpQLSfw9sGTYsHaA9D0NEuxLVVdD4QlQXDk59DFu0-E6KxLtnEhxw/viewform?usp=sf_link) (if you are taking two classes with me, you only need to fill out this questionairre once)
    * **Fill out** this brief [poll about when my office hours should be held](https://zvite.co/i/JbeK8Cyi) (if you are taking two classes with me, you only need to fill out this poll once)
    * **Sign up** for our class at Piazza (anonymous question and answer forum): [https://piazza.com/mtholyoke/spring2020/stat343](https://piazza.com/mtholyoke/spring2020/stat343)
    * **Reading**
        * Review the prerequisite material from probability and calculus.  If there are any topics from probability that you don't have memorized, please start memorizing them.  This will make the rest of this class go much more smoothly for you.  If you have any questions on this material, please don't hesitate to ask me in office hours or on Piazza.  I am happy to help with this material.
        * Over the next 1 or 2 classes we will cover material from Chapter 6 of the text.  Give those sections in the book a brief skim.
    * **Homework 0** due 5 pm Mon, Jan 27


#### Fri, Jan 24
 * **In class**, we will work on:
    * Wrap up any remaining probability examples from last class
    * Define the $t$, $F$, and $\\chi^2$ distributions; this material is in Chapter 6 of Rice.  Lecture notes: [pdf](materials/20200124_chisq_t_F/lecture_notes.pdf) **Note that there is a minor error in the lecture notes that we did not make in class:** on page 5, the denominator should be the square root of a chi squared random variable divided by its degrees of freedom.  Basically, we need to take the square root of the square of the denominator to see that we have a t-distributed random variable.
    * Lab 01.  See labs page for solutions.
 * **After class**, please:
    * **Reading:** Over the next few classes we will cover material from Sections 8.1, 8.2, 8.3, and 8.5 of the text.  Give those sections in the book a brief skim.
    * **Homework 0** due 5 pm Mon, Jan 27
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Jan 27 -- Jan 31", "
#### Mon, Jan 27
 * **In class**, we will work on:
    * Start on maximum likelihood estimation.
        * Warm up example/worksheet: [pdf](materials/20200127_mle/20200127_mle_friend_or_foe.pdf)
        * Plots to go with the example above: [pdf](materials/20200127_mle/20200127_mle_friend_or_foe_wrapup.pdf)
        * Lecture notes for maximum likelihood estimation for this example: [pdf](materials/20200127_mle/20200127_mle_lecture_notes.pdf)
        * We had a few extra minutes so we also defined an estimator (a random variable) and estimate (realized value of an estimator based on a sample, a number).
 * **After class**, please:
    * **Reading:** Over the next few classes we will cover material from Sections 8.1, 8.2, 8.3, and 8.5 of the text.  Give those sections in the book a brief skim.
    * **Homework 0** due 5 pm **today**, Mon, Jan 27

#### Wed, Jan 29
 * **In class**, we will work on:
    * **Quiz** on probability background.  This will be very similar to the examples from Wednesday Jan 22 and HW 0.  Please memorize everything on the \"Topics from probability\" document linked on the Resources page, and know how to use it.  You only need to know the informal statement of the Central Limit Theorem.
    * More on maximum likelihood estimation:
        * Example about seedlings: [pdf](materials/20200129_mle/20200127_mle_saplings.pdf) Solutions: [pdf](materials/20200129_mle/20200127_mle_saplings_solutions.pdf)
        * Lab 2.  Solutions: [GitHub](https://github.com/mhc-stat343-s2020/lab02-solutions)
 * **After class**, please:
    * **Reading:** Continue working through Section 8.5.  Also give Section 8.4 a brief skim.
    * **Homework 1** due 5 pm Wed, Feb 5


#### Fri, Jan 31
 * **In class**, we will work on:
    * More on maximum likelihood estimation:
        * Example about bird hops: [pdf](materials/20200131_mle/20200131_bird_hops.pdf)
        * Example about normal distribution.
            * Intro: [html](materials/20200131_mle/normal_likelihood.html)
            * Lecture notes: [pdf](materials/20200131_mle/lecture_notes_normal_mle.pdf)
 * **After class**, please:
    * **Homework 1** due 5 pm Wed, Feb 5
    * **Reading:** Read Section 8.4.
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Feb 03 -- Feb 07", "
#### Mon, Feb 03
 * **In class**, we will work on:
    * Example where analytically maximizing the likelihood doesn't work: [pdf](materials/20200203_mom/20200203_motivation_Gamma.pdf)
    * Method of moments.  Lecture notes: [pdf](materials/20200203_mom/lecture_notes.pdf)
    * Reminder about Taylor's theorem, from calculus review handout (linked on resources page)
    * Intro to Newton's method for optimization.  Slides: [pdf](materials/20200205_newtons_method/Newton_for_Optimization.pdf)
 * **After class**, please:
    * **Homework 1** due 5 pm Wed, Feb 5
    * **Reading**: Over the next few days, we'll explore using Newton's method to numerically optimize the log-likelihood function.  Wikipedia is a reasonably good source; you could give the following a skim:
        * Remind yourself about how Taylor's theorem works by skimming the [Wikipedia article] and/or looking at the last page of the [review of topics from calculus](resources/calculus/calculus.pdf) posted on the Resources page of the course website.  We'll review this at the beginning of class on Wednesday too.
        * [Newton's method for root finding](https://en.wikipedia.org/wiki/Newton%27s_method)
        * [Newton's method for optimization](https://en.wikipedia.org/wiki/Newton%27s_method_in_optimization)

#### Wed, Feb 05
 * **In class**, we will work on:
    * Newton's method for numerical maximization of the log-likelihood function
        * Slides posted Monday
        * Start Zero-inflated Poisson example: [html](materials/20200205_newtons_method/ZIP_newton.html)
 * **After class**, please:
    * **Homework 1** due 5 pm **today** Wed, Feb 5


#### Fri, Feb 07
 * **In class**, we will work on:
    * **Quiz** on maximum likelihood.  I'll ask you to find the maximum likelihood estimator for a model with 1 unknown parameter.
    * Newton's method for numerical maximization of the log-likelihood function
        * Finish Zero-inflated Poisson example we started last class.
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", FALSE, "Week 4: Feb 10 -- Feb 14", "
#### Mon, Feb 10
 * **In class**, we will work on:
    * Numerical maximum likelihood using Stan
        * Handout: [pdf](materials/20200207_stan_optimization/20200207_stan_optimization.pdf)
        * Lab 3
 * **After class**, please:
    * **Homework 2** due 5pm Friday Feb 14


#### Wed, Feb 12
 * **In class**, we will work on:
    * Sampling distributions, bias, variance, and mean squared error.  Lecture notes: [pdf](materials/20200212_bias_var_mse/lecture_notes.pdf)
 * **After class**, please:
    * **Homework 2** due 5pm Friday Feb 14


#### Fri, Feb 14
 * **In class**, we will work on:
    * Example of bias, variance, MSE for estimators of the variance of a normal distribution.  Lecture notes: [pdf](materials/20200214_mse_bayes_set_up/lecture_notes.pdf)
    * We didn't have time to get to Lab 4, but maybe you could take a quick look at it on your own?
    * Motivation for subjective probability intervals: [pdf](materials/20200214_mse_bayes_set_up/20200214_subjective_intervals.pdf)
 * **After class**, please:
    * **Homework 2** due 5pm **today** Friday Feb 14
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", FALSE, "Week 5: Feb 17 -- Feb 21", "
#### Mon, Feb 17
 * **In class**, we will work on:
    * Wrap up lab on bias, variance, and MSE
    * Wrap up subjective probability intervals/subjective interpretation of probability
    * Intro to Bayesian inference
        * Lecture notes on Binomial example: [pdf](materials/20200217_bayes_binomial/lecture_notes.pdf)
        * We also did the first example on this worksheet: [pdf](materials/20200219_bayes_practice/20200219_bayes_practice.pdf)
 * **After class**, please:


#### Wed, Feb 19
 * **In class**, we will work on:
    * More on Bayesian inference:
        * Lab 6
        * Finish examples from practice worksheet last class.
 * **After class**, please:
    * **Homework 3** due Wed. Feb 26


#### Fri, Feb 21
 * **In class**, we will work on:
    * Bayesian credible intervals: posterior percentiles, highest posterior density.  Partial lecture notes are here, but I also discussed highest posterior density: [pdf](materials/20200221_more_bayes_practice/lecture_notes_bayes_point_interval_estimates.pdf)
    * Start on analysis of normal distribution from a Bayesian perspective.
        * Lecture notes: [pdf](materials/20200221_more_bayes_practice/bayes_normal_notes.pdf).  Note that for case 1 (unknown mean, known variance) I mixed up the notation a little towards the end of page 1 of these notes.  The stuff I wrote in class was correct.
        * Plots illustrating MSE for Bayesian estimator of the mean when the variance is known: [pdf](materials/20200221_more_bayes_practice/20200221_normal_univar_bayes.pdf)
    * Another practice example we didn't have time for: [pdf](materials/20200221_more_bayes_practice/20200221_more_bayes_practice.pdf).  Solutions: [pdf](materials/20200221_more_bayes_practice/20200221_more_bayes_practice_solutions.pdf)
 * **After class**, please:
    * **Homework 3** due Wed. Feb 26
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", FALSE, "Week 6: Feb 24 -- Feb 28", "
#### Mon, Feb 24
 * **In class**, we will work on:
    * Finish examples of estimation for normal distribution from last class.
    * Introduce Monte Carlo integration:
        * Lecture notes: [pdf](materials/20200224_mc_integration/numerical_integration_notes.pdf)
        * Examples: [pdf](materials/20200224_mc_integration/20200224_mc_integration.pdf)
 * **After class**, please:
    * **Homework 3** due Wed. Feb 26


#### Wed, Feb 26
 * **In class**, we will work on:
    * Finish examples from last class
 * **After class**, please:
    * **Homework 3** due **Thursday Feb. 27**


#### Fri, Feb 28
 * **In class**, we will work on:
    * Some additional Monte Carlo integration examples: [pdf](materials/20200226_mcmc/20200226_more_mc_integration_examples.pdf)
    * Introduce MCMC
        * [pdf](materials/20200226_mcmc/20200226_bayes_MCMC_Metropolis.pdf)
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", FALSE, "Week 7: Mar 02 -- Mar 06", "
#### Mon, Mar 02
 * **In class**, we will work on:
     * Finish MCMC (correction to last pages of handout from last class) and lab on MCMC:
         * [pdf](materials/20200302_mcmc_stan_fix/20200032_bayes_stan.pdf)
     * Quiz 3
 * **After class**, please:


#### Wed, Mar 04
 * **In class**, we will work on:
    * Overview of next week or two: [pdf](materials/20200304_Fisher_information/notes_upcoming.pdf)
    * Fisher information
        * Motivation: [pdf](materials/20200304_Fisher_information/20200304_large_sample_information.pdf)
        * Lecture notes: [pdf](materials/20200304_Fisher_information/notes_fisher.pdf)
        * Connection to Taylor series: [pdf](materials/20200304_Fisher_information/20200304_information_Taylor.pdf)
 * **After class**, please:
    * If you want reading for the material we'll cover in the next few days, you can refer to the following sources (in order of how useful I think they are):
        * https://ocw.mit.edu/courses/mathematics/18-443-statistics-for-applications-fall-2006/lecture-notes/lecture3.pdf
        * Rice Section 8.5.2
        * http://www.stat.cmu.edu/~larry/=stat705/Lecture9.pdf

#### Fri, Mar 06
 * **In class**, we will work on:
    * Large-sample approximation to sampling distribution of MLE
        * Hand out with proof: [pdf](materials/20200306_normal_approx_mle/20200306_normal_approx_mle_preliminaries.pdf)
        * Hand out with conditions: [pdf](materials/20200306_normal_approx_mle/graymleconditions.pdf)
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", FALSE, "Week 8: Mar 09 -- Mar 13", "
#### Mon, Mar 09
 * **In class**, we will work on:
     * Large-sample normal approximation to sampling distribution of MLE (Continuing handouts from last class)
 * **After class**, please:


#### Wed, Mar 11
 * **In class**, we will work on:
    * Consistency and Efficiency
        * Notes: [pdf](materials/20200311_consistency_efficiency_lab_mle_sampling/consistency_efficiency_CRLB.pdf)
        * Set up for lab 10: [pdf](materials/20200311_consistency_efficiency_lab_mle_sampling/20200311_pareto_mle_sampling.pdf)
 * **After class**, please:


#### Fri, Mar 13
 * **In class**, we will work on:
    * No new material.
 * **After class**, please:
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", FALSE, "Week 9: Mar 16 -- Mar 20", "
#### Mon, Mar 16
 * **No Class**: Midsemester Break.  Safe travels!


#### Wed, Mar 18
 * **No Class**: Midsemester Break.  Safe travels!


#### Fri, Mar 20
 * **No Class**: Midsemester Break.  Safe travels!
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", FALSE, "Week 10: Mar 23 -- Mar 27", "
#### Mon, Mar 23
 * **No Class**: Midsemester Break.  Safe travels!


#### Wed, Mar 25
 * **No Class**: Midsemester Break.  Safe travels!


#### Fri, Mar 27
 * **No Class**: Midsemester Break.  Safe travels!
")
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", FALSE, "Week 11: Mar 30 -- Apr 03", '
#### Mon, Mar 30
 * **In class**, we will work on:
    * Reminder/overview of recent topics:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/qVKYEUITtPg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200330_Bayes_large_sample/notes.pdf)
        * Errors:
            * At about 16:50 in the video, I should have written $\\hat{\\Theta}^{MLE}$
    * Statement of Theorem: Normal approximation to posterior distribution for large $n$.
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/wvWcNwnZW4M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200330_Bayes_large_sample/20200330_normal_approx_posterior_notes.pdf)
        * Errors:
            * At about minute 4:00 in the video, I incorrectly state that the marginal posterior distribution for the mean in a Bayesian analysis of a normal distribution with unknown variance is normal.
    * Proof Part 1: Prior doesn\'t matter:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/0I62_rpvy0s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200330_Bayes_large_sample/20200330_log_posterior_contributions_notes.pdf)
    * Proof Part 2: 2nd order Taylor approximation:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/yagz_0HAMvc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200330_Bayes_large_sample/Proof.pdf)
 * **After class**, please:


#### Wed, Apr 01
 * **In class**, we will work on:
    * Example of finding a normal approximation to the posterior distribution and using that approximation to find a credible interval:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/FdQErLxNtvM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200401_Bayes_large_sample_CI/binomial_approx_posterior_ci.pdf)
    * Worksheet and lab:
        * Worksheet (written part introducing lab 11 -- do this before lab 11)
            * Written part: [pdf](materials/20200401_Bayes_large_sample_CI/lab11_bayes_normal_approx_worksheet.pdf)
            * Solutions to written part: [pdf](materials/20200401_Bayes_large_sample_CI/lab11_bayes_normal_approx_worksheet_solutions.pdf)
        * Now go on to lab 11, distributed via GitHub.  Solutions will be posted on the labs page some time on Wednesday April 1.
 * **After class**, please:
    *  Finish worksheet and lab from today.


#### Fri, Apr 03
 * **In class**, we will work on:
    * Taking stock of where we are in the class:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/OT5eVFHMRJk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    * Motivating example for confidence intervals:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/SkDIzdRh_r4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200403_freq_CI/20200403_freq_ci_motivation_normal_body_temps.pdf)
    * Defining confidence intervals, and an example of a confidence interval derivation:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/ZZVSkkh_jOQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200403_freq_CI/20200403_freq_ci_example_normal_body_temps.pdf)
        * Errors:
            * At about minute 36 I wrote down the wrong formula for the confidence interval.  The formula should be $[\\bar{x} - t_{n-1}(1 - \\frac{\\alpha}{2}) \\frac{s}{\\sqrt{n}}, \\bar{x} - t_{n-1}(\\frac{\\alpha}{2}) \\frac{s}{\\sqrt{n}}]$
    * The videos were longer than I originally planned, so we\'ll do the example/lab next class.
')
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", FALSE, "Week 12: Apr 06 -- Apr 10", '
#### Mon, Apr 06
 * **In class**, we will work on:
    * More details about confidence intervals: pivotal quantities, one-sided intervals
        * <iframe width=\"560\" height=\"315\" src="https://www.youtube.com/embed/rk7e4Zy30Io" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200406_freq_CI/More_CI.pdf)
    * Additional confidence interval example (variance of a normal distribution):
        * Written part: [pdf](materials/20200406_freq_CI/20200406_freq_ci_normal_var.pdf)
        * Written part solutions: [pdf](materials/20200406_freq_CI/20200406_freq_ci_normal_var_sol.pdf)
        * Lab 12
 * **After class**, please:


#### Wed, Apr 08
 * **In class**, we will work on:
    * Motivation for getting confidence intervals based on a large-sample normal approximation to a sampling distribution:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/RQKLSFb7eYk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200408_wald_CI/Wald_motivation.pdf)
    * Example of getting confidence intervals based on a large-sample normal approximation to a sampling distribution:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/99VSt5V_r-0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200408_wald_CI/Example_notes.pdf)
        * Results from R: [pdf](materials/20200408_wald_CI/20200408_poisson_large_sample_ci.pdf)
    * Example for you to do: Rayleigh distribution
        * Written part: [pdf](materials/20200408_wald_CI/20200408_rayleigh_large_sample_ci.pdf)
        * Written part solutions: [pdf](materials/20200408_wald_CI/20200408_rayleigh_large_sample_ci_sol.pdf)
        * Lab 13

#### Fri, Apr 10
 * **In class**, we will work on:
    * There is a little more content here than would fit into one class day.  I\'ll do a little less on Monday.
    * Introduction to bootstrap for estimating a sampling distribution
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/9qAJUQBbNjY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Annotated notes: [pdf](materials/20200410_bootstrap/20200410_bootstrap_annotated_video1.pdf)
    * Example of bootstrap for estimating the distribution of the mean for a Poisson distribution
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/4VCGLYTW-hw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Annotated notes: [pdf](materials/20200410_bootstrap/20200410_bootstrap_example_annotated.pdf)
        * Handout from video 1 with new notes I made for this video: [pdf](materials/20200410_bootstrap/20200410_bootstrap_annotated_video2.pdf)
        * R Markdown document for example: [Rmd](materials/20200410_bootstrap/20200410_bootstrap_example.Rmd) [GitHub](https://github.com/mhc-stat343-s2020/20200410_bootstrap_example)
')
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", FALSE, "Week 13: Apr 13 -- Apr 17", '
#### Mon, Apr 13
 * **In class**, we will work on bootstrap confidence intervals
    * Materials used throughout all videos today and next class
        * Handout without my writing on it:  [pdf](materials/20200413_bootstrap_CIs/20200413_bootstrap_CIs.pdf)
        * Handout with my notes on it: [pdf](materials/20200413_bootstrap_CIs/20200413_bootstrap_CIs_annotated.pdf)
        * R markdown file used to generate handout: [Rmd](materials/20200413_bootstrap_CIs/20200413_bootstrap_CIs.Rmd) [GitHub](https://github.com/mhc-stat343-s2020/20200413_bootstrap_ci_example)
    * Introduction and set up:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/-PmfQRHnZKw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Errors and Notes:
            * At about 6:40, I gave an incorrect formula for the estimated standard error of the sample mean.  The correct formula is $\\widehat{SE}(\\bar{X}) = S/\\sqrt{n} = \\left[ \\frac{\\sum_{i=1}^n (X_i - \\bar{X})^2}{n - 1} \\right]^{0.5} / \\sqrt{n}$
            * As I made this video, I claimed we really needed a bootstrap for this case.  As I looked at the example more, I decided that although I\'m most comfortable with a bootstrap based interval in this example, probably other approaches would also work OK.
    * Percentile bootstrap confidence intervals:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/TfhAqithJQU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    * Bootstrap t confidence intervals when a formula is available to calculate the estimated standard error.
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/xEQrAfHfqCk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


#### Wed, Apr 15
 * **In class**, we will work on:
    * Continuing with handout from April 13
    * Bootstrap t confidence intervals when no formula is available to calculate the estimated standard error.  Part 1: concepts
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/VqBxWaJOiNY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    * Bootstrap t confidence intervals when no formula is available to calculate the estimated standard error.  Part 2: code walk-through
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/XpzOBgX_HyU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    * Lab on bootstrap confidence intervals
 * **After class**, please:


#### Fri, Apr 17
 * **In class**, we will work on:
    * Reminder about likelihood ratios:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/n0R5EcV0Z00" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes on worksheet from 2020-03-04.  We talked about this handout in more detail that day.  [pdf](materials/20200417_intro_hypothesis_test/20200417_large_sample_information.pdf)
    * First examples (more to come on Monday):
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/ZT5Odl6-A_Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200417_intro_hypothesis_test/20200417_intro_test_annotated.pdf)
 * **After class**, please:
')
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", TRUE, "Week 14: Apr 20 -- Apr 24", '
#### Mon, Apr 20
 * **In class**, we will work on:
    * Warm up example for likelihood ratio tests.  **I suggest giving the problem a try before watching the solutions video or looking at the solutions pdf.**
        * Warm up example: [pdf](materials/20200420_more_hypothesis_test/20200420_likelihood_ratio_practice.pdf)
        * Solutions: [pdf](materials/20200420_more_hypothesis_test/20200420_likelihood_ratio_practice_sol.pdf)
        * Solutions video: <iframe width="560" height="315" src="https://www.youtube.com/embed/Vge3cgogRo4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    * Example of likelihood ratio tests for a normal distribution.  **I suggest giving the problem a try before watching the solutions video or looking at the solutions pdf.**
        * Example: [pdf](materials/20200420_more_hypothesis_test/20200420_test_example_normal.pdf)
        * Solutions: [pdf](materials/20200420_more_hypothesis_test/20200420_test_example_normal_sol.pdf)
        * Solutions video: <iframe width="560" height="315" src="https://www.youtube.com/embed/DaiF_ukQXjQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    * Lab 15, which follows up on the second example above.


#### Wed, Apr 22
 * **In class**, we will work on:
    * Introduction to decisions with hypothesis tests; errors; limitations of the framework
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/uqEBHUThjN8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200422_errors/Htest_decisions.pdf)
    * Type I Errors:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/HH00y4F6_qI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200422_errors/Errors.pdf)
    * Type II Errors and Power:
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/eFSbspF-wNs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200422_errors/Type_II_errors_and_power.pdf)


#### Fri, Apr 24
 * **In class**, we will work on:
    * Warm Up about Power Functions **I suggest giving the problem a try before watching the solutions video or looking at the solutions pdf.**
        * Warm up: [pdf](materials/20200424_power/20200424_power_warmup.pdf)
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/VSbo8VWYi7w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Annotated solutions: [pdf](materials/20200424_power/20200424_power_warmup_sol_annotated.pdf)
    * Motivation for Neyman Pearson Lemma **I suggest giving the problem a try before watching the solutions video or looking at the solutions pdf.**
        * Warm up: [pdf](materials/20200424_power/20200424_np_motivation.pdf)
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/ddh3kvYkSjQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Annotated solutions: [pdf](materials/20200424_power/20200424_np_motivation_sol_annotated.pdf)
    * Set up for Neyman Pearson Lemma: reminder and more detail about likelihood ratios
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/ECorAM_z48M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Annotated pdf: [pdf](materials/20200424_power/20200424_likelihood_ratios_annotated.pdf)
    * Statement and proof of Neyman Pearson Lemma
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/l3EezWQRc_I" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200424_power/NP.pdf)
')
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", TRUE, "Week 15: Apr 27 -- May 01", '
#### Mon, Apr 27
 * **In class**, we will work on:
    * Composite likelihood ratio tests; derivation of t tests
        * <iframe width="560" height="315" src="https://www.youtube.com/embed/xmHv1dBfb80" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        * Notes: [pdf](materials/20200427/TTest.pdf)

')
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: May 04 -- May 08", "We **will** have a final exam in this class.")
```

